spring.application.name=Apis

# Server configuration
server.port=8081
server.servlet.context-path=/myapp

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db1
spring.datasource.username=root
spring.datasource.password=SitaRamji@21
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.springPractice=DEBUG

# Custom property
app.title=My Spring Boot Application
